### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Artuto** [ProtocolSupport/ProtocolSupportPocketIssues#61]
- [ ] Anvils dont work
- [ ] ~~Enchanting tables dont work~~ (see https://github.com/ProtocolSupport/ProtocolSupportPocketIssues/issues/14)
- [ ] ~~Smooth Quartz are remapped incorrectly as nether bricks.~~(fixed)
- [ ] ~~Riding an entity moves you under the ground (using CMI's stairs as chairs).~~ (see https://github.com/ProtocolSupport/ProtocolSupportPocketIssues/issues/93)
- [ ] ~~Some colored terracotta blocks appear invisible when placed.~~(fixed)
- [ ] ~~Can't interact with Citizens or Shopkeepers NPCs.~~ (see https://github.com/ProtocolSupport/ProtocolSupportPocketIssues/issues/92)

**Comment by WesleyVanNeck** [comment]
yeah true. I hope @colinrgodsey is gone fix it soon tm

**Comment by Artuto** [comment]
Added some more issues.

**Comment by magicus** [comment]
@Artuto I checked nether bricks; they look just fine to me. The full block, the slab and the fence. And the items. 

Are you using 1.9? 

I also verified the handful of coloured terracotta that I had lying around (about half the possible colors), they all looked OK to me.

**Comment by Artuto** [comment]
Actually the user confirmed me, and its the other way around, smooth quartz is apparently nether bricks.

**Comment by magicus** [comment]
@Artuto I see.

Smooth quartz issue is now fixed.

Do you have any more input as to which terracotta blocks are having problems?

**Comment by magicus** [comment]
I can confirm that light gray glazed terracotta is missing. All other, normal and glazed, terracotta works fine.

**Comment by magicus** [comment]
@Artuto We have two open bugs on anvils:
https://github.com/ProtocolSupport/ProtocolSupportPocketIssues/issues/84 and https://github.com/ProtocolSupport/ProtocolSupportPocketIssues/issues/83.

Is this what you mean when you say anvils do not work, or is there even more use cases that I have missed that are broken?

**Comment by Artuto** [comment]
Nope. But its related. Just renaming them crashes.

**Comment by magicus** [comment]
Hm, I though renames worked OK for me? But maybe it's intermittent, I managed to add an enchantment to a sword when I tried to repro this issue, and it crashed for me consistently before.

**Comment by magicus** [comment]
AFAICT, all separate issues reported here has either been fixed, or is handled in a separate bug. Closing this umbrella bug.

**Comment by Artuto** [comment]
Reopening because this still has some issues reported above.

- Smooth quartz is a stone block in inventory. Works fine when placed in world. ![](https://cdn.discordapp.com/attachments/497480149059633152/558417441307361290/Screenshot_2019-03-21-16-28-27.png)

- Colored terracotta placing still is buggy. position is changed when its placed.

**Comment by magicus** [comment]
I have a fix for colored terracotta orientation in a PR.

**Comment by magicus** [comment]
I'm opening a separate bug for smooth quartz item remap.
